### ISSUE TITLE
Fields for Flood Form

### ISSUE THREAD

**Issue by susanfiu** [Code-for-Miami/queen-tide#2]
Below are fields for the flood form. Fields with an asterisk are required.

- **Name** \*
- E-mail 
- **Date of Report**: (auto fill with today's date, but allow for changes) \*
- **Time of Report**: (auto fill with current time, but allow for changes) \*
- **Location**: (auto fill with current location, but allow user to enter a different location) \*
- Description: Text field
- Closeup of Flood: (button to upload photo)
- Context of Flood: (button to upload photo)
- Water Depth Fields:
    - Water Depth: (numeric field)
    - Water Depth Units: (drop-down menu with two choices: inches, centimeters)
    - Water Depth Photo: (button to upload photo)
- Salinity Fields:
    - Salinity: (numeric field)
    - Salinity Units: (drop-down menu with one choice: ppt)
    - Salinity Photo: (button to upload photo)
- Water Sample Fields:
    - Water Bottle Number: (numeric field)
    - Water Bottle Photo: (button to upload photo)
- Field Notes: Text field

**Comment by differentsmoke** [comment]
@susanfiu I edited your comment a little bit. 

I have one question:
>Salinity Units: (drop-down menu with **one choice**: ppt)

Is this field necessary, if we will always use the same unit?

**Comment by differentsmoke** [comment]
@StephanieCherubin  I understand you are taking care of this issue?

**Comment by StephanieCherubin** [comment]
Yes, I am.

**Comment by differentsmoke** [comment]
See below for the Flood model schema:

```ruby
create_table "floods", force: :cascade do |t|
    t.string "first_name"
    t.string "last_name"
    t.string "email"
    t.datetime "date_of_report"
    t.text "description"
    t.decimal "latitude", precision: 10, scale: 6
    t.decimal "longitude", precision: 10, scale: 6
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "address"
    t.string "close_up_file_name"
    t.string "close_up_content_type"
    t.integer "close_up_file_size"
    t.datetime "close_up_updated_at"
    t.string "context_file_name"
    t.string "context_content_type"
    t.integer "context_file_size"
    t.datetime "context_updated_at"
    t.decimal "water_depth"
    t.integer "water_depth_units"
    t.decimal "salinity"
    t.integer "bottle_number"
    t.string "water_depth_photo_file_name"
    t.string "water_depth_photo_content_type"
    t.integer "water_depth_photo_file_size"
    t.datetime "water_depth_photo_updated_at"
    t.string "salinity_photo_file_name"
    t.string "salinity_photo_content_type"
    t.integer "salinity_photo_file_size"
    t.datetime "salinity_photo_updated_at"
    t.string "bottle_photo_file_name"
    t.string "bottle_photo_content_type"
    t.integer "bottle_photo_file_size"
    t.datetime "bottle_photo_updated_at"
  end
```
