### ISSUE TITLE
Permission - Please add me

### ISSUE THREAD

**Issue by nazimco** [Code-for-Miami/queen-tide#7]
I tried to push but I don’t have permission I got an error message:
Permission to Code-for-Miami/queen-tide.git denied to nazimco.

I committed and wanted to add the accordion style menu to the branch I created.

<img width="462" alt="screen shot 2018-08-06 at 10 47 24 pm" src="https://user-images.githubusercontent.com/39137107/43751425-d5778138-99ca-11e8-8fb6-d106836c35e4.png">

**Comment by nazimco** [comment]
<img width="1440" alt="screen shot 2018-08-07 at 11 55 24 am" src="https://user-images.githubusercontent.com/39137107/43787382-dc247a04-9a38-11e8-81bc-8fede84a5d01.png">

**Comment by differentsmoke** [comment]
@nazimco I believe you have been already invited, so I'm closing this. If this is not the case please reopen the issue.
